services:
  consul:
    image: hashicorp/consul:latest
    container_name: "consul"
    ports:
      - "5001:8500"

  pedidosapi:
    image: lizorrane/pedidosapi:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "4002:8080"

  pizzaapi:
    image: lizorrane/pizzaapi:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "4003:8080"

  notificacoesapi:
    image: brunoosilva/ms-notificacoesservice
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - Consul__Discovery__Hostname=notificacoesapi
    ports:
      - "4001:8080"

  apigateway:
    image: lizorrane/apigateway:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "3001:8080"

  fake-smtp-server:
    image: gessnerfl/fake-smtp-server:latest
    container_name: "fake-smtp-server"
    restart: always
    ports:
      - 7001:8080
      - 7002:8081